

APP_NAME_TAG = '<<APP_NAME>>'
DEFAULT_QUESTION_TAG = '##QUESTION_DETAIL##'
DEFAULT_QUESTION_OTHER = '##QUESTION_OTHER##'
DEFAULT_QUESTION_VALUE_ALL = '##ALL##'
DEFAULT_QUESTION_VALUE_NONE = '##NONE##'
DEFAULT_QUESTION_VALUE_OTHER = '##OTHER##'
DEFAULT_ANSWER_OTHER = 'Other'
